[project]
name = "grasp-cube-sample"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mani_skill-nightly",
    "tensorboard>=2.20.0",
    "tensordict>=0.10.0",
    "torch",
    "wandb>=0.23.0",
]
